# Generated by Django 5.1.6 on 2025-03-04 17:35

from django.db import migrations
import phonenumbers

def copy_owners_phonenumber_to_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owners_phonenumber = flat.owners_phonenumber
        try:
            owner_pure_phone = phonenumbers.parse(owners_phonenumber, "RU")
            if phonenumbers.is_valid_number(owner_pure_phone):
                flat.owner_pure_phone = owner_pure_phone
                flat.save()
        except:
            pass


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = ''
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone_alter_complaint_id_and_more'),
    ]

    operations = [
        migrations.RunPython(
            copy_owners_phonenumber_to_owner_pure_phone,
            move_backward
        )
    ]
