# Generated by Django 5.1.6 on 2025-03-04 18:17

from django.db import migrations


def copy_from_flat_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner.objects.get_or_create(
            full_name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        )


def move_backward(apps, schema_editor):
    owner = apps.get_model('property', 'Owner')
    owner.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(copy_from_flat_to_owner, move_backward)
    ]
