# Generated by Django 5.1.6 on 2025-03-05 19:16

from django.db import migrations


def link_flats_to_owner(apps, schemaeditor):
    Flat = apps.get_model('property', 'Flat')
    Owner= apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner = Owner.objects.filter(
            full_name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        ).first()
        if owner:
            flat.owners.add(owner)
            flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owners.clear()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20250304_2117'),
    ]

    operations = [
        migrations.RunPython(link_flats_to_owner, move_backward)
    ]
